### ISSUE TITLE
Add Zeebe Spring to documentation

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/camunda-cloud-documentation#130]
The Zeebe Spring project is an alternative for people to start implementing applications with Zeebe in Java. In many ways it provides a more convenient starter experience for people familiar with the Spring framework.

I think we should mention it in _product-manuals/clients/other-clients_

**Comment by akeller** [comment]
@berndruecker do you want to move the Zeebe Spring project into our Clients > Community Clients part of the official documentation?

**Comment by berndruecker** [comment]
Generally happy to do it - but I am not sure if I will be able to make it before going on holiday end of the month. I put it on my list and try - but can't commit just yet.
But I totally agree that this makes sense (and I even cross fingers most Java people start with the Spring Boot integration instead of plain)

**Comment by berndruecker** [comment]
Created a PR: https://github.com/camunda-cloud/camunda-cloud-documentation/pull/321
