### ISSUE TITLE
I can read how to evaluate DMN decisions with a business rule task

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/camunda-cloud-documentation#421]
With Zeebe 1.3, we implement that a business rule task can evaluate a DMN decision.

We should update the docs of the [business rule task](https://docs.camunda.io/docs/reference/bpmn-processes/business-rule-tasks/business-rule-tasks/) and describe how it must be configured.

**Comment by korthout** [comment]
Ping @barmac, just to keep you in the loop

**Comment by akeller** [comment]
Recapping a meeting we had this morning led by @saig0 with myself, @korthout, @christinaausley and @barmac:

* @akeller will copy existing [Camunda Platform docs for DMN](https://docs.camunda.org/manual/7.16/user-guide/dmn-engine/) into a branch with a PR next week (last week of Feb)
* @saig0 will review and rewrite for the SaaS first, Camunda Cloud-based experience since the DMN engines for Camunda Cloud and Camunda Platform are different yet similar.
* @barmac assess screenshots, ideally, part of the automated screenshot process Modeler uses
* @akeller to sync with @berndruecker to update [Migrating from Camunda Platform](https://docs.camunda.io/docs/guides/migrating-from-Camunda-Platform/) guide to include DMN
* @christinaausley will author new basic DMN guide for beginners modeling in DMN (similar to [Automating a Process in BPMN](https://docs.camunda.io/docs/guides/automating-a-process-using-bpmn/))
* target docs completion in April where @akeller and @christinaausley will do a final review before publishing

**Comment by korthout** [comment]
Documentation for the business rule task should keep in mind:

>Note that the input mappings of the business rule task are applied again when an incident is resolved. The mappings could override variables that were changed to resolve the incident. We should mention the behavior in the docs.

https://github.com/camunda-cloud/zeebe/issues/8095#issuecomment-963203798

**Comment by saig0** [comment]
Closed by #421 :rocket:
