### ISSUE TITLE
Overhaul the structure of the self-managed docu section

### ISSUE THREAD

**Issue by Hafflgav** [camunda-cloud/camunda-cloud-documentation#640]
As discovered in #609 it is a good idea to overhaul the structure of the Camunda Cloud Self-Managed documentation. 

**Benefit Hypothesis**: The separation between deployment options is obvious to a reader. Minimise questions and problems a user might have during the setup of a self-managed Camunda-Cloud solution. 

**Proposed Structure**:

SelfManaged:
* Kubernetes
  * Zeebe
  * Operate
  * Tasklist
* Docker
  * Zeebe
  * Operate
  * Tasklist 

In order to achieve this the current chapters need to be split up and separated accordingly. 

**Relevant Stakeholders**: @Zelldon, @akeller & @felix-mueller

**Comment by akeller** [comment]
I think this is a great idea. I do want the overall focus of the docs to highlight deploying all the components together (Zeebe, Operate, Tasklist, Optimize, Identity, etc.). Do we need to have separate pages for each component? Or is that because there are separate instructions for each component?

For Docker, I know @menski was working on updates to the docker-compose file that's part of the Get Started repo that's technically not a production-supported pathway. Similar to what I said above, if we want to highlight deploying all the components together, do we need to have a separate page for each component?

**Comment by Hafflgav** [comment]
I agree with you @akeller that we should focus this guide on deploying all components together. 
In my humble opinion we are still going to need some more sub-pages in order to properly display information about to configure each of the components properly. I think this will make it easier to find the right configuration parameter you are looking for. 

To me this configuration either happens in the values.yaml for Kubernetes or in the docker-compose.yaml for Docker. Due to these similarities I would try to structure the section the same way.

**Comment by Zelldon** [comment]
Maybe sections are enough for the configurations :)

**Comment by akeller** [comment]
I'll let you two write the content and we can see if the pages are super short, then let's go to sections. 😄

**Comment by akeller** [comment]
As discussed over Slack, if I have time later this week I can take a look at trying to tackle this. Otherwise, this may not make release-1.4.0 but can be revisited after.

**Comment by berndruecker** [comment]
Related to https://github.com/camunda-cloud/camunda-cloud-documentation/issues/670

**Comment by berndruecker** [comment]
I implemented this and unfortunately pushed it directly to the 1.4.0 branch instead of a PR (See slack). Sorry!
But I made sure the build is running again and you can see the final result here: https://c8.docs.camunda.io/docs/self-managed/platform-deployment/

@akeller I know this makes your life with reviewing harder - I am really sorry! Put it on my wine bill 🙈

**Comment by akeller** [comment]
Oof I will compare to what's in production I guess? I also see a few typos. 🍷

**Comment by Zelldon** [comment]
Maybe we just revert the commits ? And create a separate PR? Might make the life from @akeller easier?

**Comment by berndruecker** [comment]
I think it would be relatively safe to just have a quick look at the documents in https://github.com/camunda-cloud/camunda-cloud-documentation/tree/release-1.4.0/docs/self-managed/platform-deployment / (at least for copy edits/typos) - they all had changes and lots of content got copied from different files to a joined file anyway - so the DIFF might not be too useful. Add it to the 🍷 bill (hah - I did not know that we have the icon here till now - so it might have been worth it 🙈 )

**Comment by akeller** [comment]
Will add review commits to #781

**Comment by berndruecker** [comment]
Yeah - why not - probably a bit less wordy indeed. In terms of "understanding it quickly" maybe a table would be best (there the wordiness is less of a Problem 
 Component | Type of component | Requirements

- but on the other hand I think all is good enough for know (and we can still change it later on)

**Comment by akeller** [comment]
The PR is merged to the release branch. Can we close this issue or does other work still remain?
