### ISSUE TITLE
Micronaut Launch doesn't load from docs

### ISSUE THREAD

**Issue by akeller** [camunda-cloud/camunda-cloud-documentation#856]
Hi @tobiasschaefer, I noticed [this link](https://micronaut.io/launch?name=jobworker&features=zeebe) on [this page](https://docs.camunda.io/docs/apis-clients/community-clients/micronaut/) doesn't quite work for me and I see this:

<img width="264" alt="image" src="https://user-images.githubusercontent.com/1051363/165363681-5aca86bf-d3f7-4196-99d8-053a8f8c657b.png">

This doesn't seem to happen when I go straight to the website and click the launch button. Any ideas on how we can improve this so the page loads successfully? Otherwise, I'd like to navigate to the Micronaut site and let people hit "Launch" themselves.

**Comment by tobiasschaefer** [comment]
Hi @akeller ,

thanks for contacting me.

It works for me. I tested with
* Chrome on MacOS
* Safari on MacOS
* Edge on Windows
* Firefox on Windows

The screenshot says "You need to enable JavaScript to run this app". Have you possibly disabled JavaScript? In that case you should actually have problems with some other web sites as well...

I'd prefer not to navigate to the Micronaut site and simple let the people hit "Launch" because
1. The parameters to preselect the name "jobworker" and more importantly the feature "zeebe" would need to be entered manually
2. It would be an unnecessary click in between

Could you please check if this might be an unusual browser configuration on your side. Thanks.

**Comment by akeller** [comment]
This seems to have resolved itself for me - I'm running Chrome on MacOS. I'll go ahead and close this, not sure what happened. I have JS running and no problems with other sites. 🤷‍♀️
